pygments: false
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/mchun0630/trialpdb2pqr.git
baseurl:  https://github.com/mchun0630/trialpdb2pqr
markdown: kramdown
